volumes:
  netta_storage:
    external: true
  postgresnetta_storage:
    external: true

networks:
  reverse-proxy:
    external: true

x-n8n: &service-netta
  image: n8nio/n8n:latest
  networks:
      - reverse-proxy
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgresnetta
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_BASIC_AUTH_ACTIVE=true
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - N8N_RUNNERS_ENABLED=true
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - OLLAMA_HOST=ollama:11434
    - N8N_USER_MANAGEMENT_DISABLED=false
    - N8N_OWNER_MODE=false
    - N8N_HOST=netta.luigi.ip-ddns.com/
    - WEBHOOK_URL=netta.luigi.ip-ddns.com/

  env_file:
    - .env

services:
  postgresnetta:
    image: postgres:16-alpine
    hostname: postgresnetta
    networks:
      - reverse-proxy
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgresnetta_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  netta-import:
    <<: *service-netta
    hostname: netta-import
    container_name: netta-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/demo-data/credentials && n8n import:workflow --separate --input=/demo-data/workflows"
    volumes:
      - ./n8n/demo-data:/demo-data
    depends_on:
      postgresnetta:
        condition: service_healthy

  netta:
    <<: *service-netta
    hostname: netta
    container_name: netta
    restart: unless-stopped
    ports:
      - 5679:5678
    volumes:
      - netta_storage:/home/node/.n8n
      - ./n8n/demo-data:/demo-data
      - ./shared:/data/shared
    depends_on:
      postgresnetta:
        condition: service_healthy
      netta-import:
        condition: service_completed_successfully

